#!/bin/bash
#Script to monitor goings on of masternnode
n=1
coin="Desire"
addr1="D9zvwQuZBbW89ZaPt6jTLSFCY3TKWikXez"
addr2=""
addr3=""

while [ $n -le 10000 ]
do
   echo "Monitoring" $coin
   echo "Current script run is" $n 
   echo "Current mining block is:" 
   ~/Desire/src/desire-cli masternode current | grep "height"

    for lookup in $addr1 $addr2 $addr3 
       do
          echo "Address is" $lookup
          echo "Masternode status:"
          ~/Desire/src/desire-cli masternode status | grep status  
          echo "Upcoming address for payment?"
          payout=$(~/Desire/src/desire-cli masternode winners | grep $lookup )
          if [[ $payout ]]
            then 
              echo $coin "payment is coming (block, payee): " $payout 
              echo $payout >> ~/dsr_log_$lookup
          else
              echo "No upcoming payment"  
          fi
        echo "Payment list:"
          ~/Desire/src/desire-cli masternode winners
     done
   sleep 60 
   n=$(( n+1 ))
done
